/* tslint:disable */
/* eslint-disable */
/**
 * Glista API
 * Glista ASP.NET Core Web API.
 *
 * The version of the OpenAPI document: v1
 * Contact: mitjajancic@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddNewEventGroupPilotDTO
 */
export interface AddNewEventGroupPilotDTO {
    /**
     * 
     * @type {number}
     * @memberof AddNewEventGroupPilotDTO
     */
    teamId: number;
    /**
     * 
     * @type {number}
     * @memberof AddNewEventGroupPilotDTO
     */
    pilotId: number;
    /**
     * 
     * @type {number}
     * @memberof AddNewEventGroupPilotDTO
     */
    eventGroupId: number;
}


