/* tslint:disable */
/* eslint-disable */
/**
 * Glista API
 * Glista ASP.NET Core Web API.
 *
 * The version of the OpenAPI document: v1
 * Contact: mitjajancic@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddNewTeamDTO
 */
export interface AddNewTeamDTO {
    /**
     * 
     * @type {string}
     * @memberof AddNewTeamDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddNewTeamDTO
     */
    notes?: string | null;
}


