/* tslint:disable */
/* eslint-disable */
/**
 * Glista API
 * Glista ASP.NET Core Web API.
 *
 * The version of the OpenAPI document: v1
 * Contact: mitjajancic@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddNewUserDTO
 */
export interface AddNewUserDTO {
    /**
     * 
     * @type {string}
     * @memberof AddNewUserDTO
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof AddNewUserDTO
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof AddNewUserDTO
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof AddNewUserDTO
     */
    email: string;
    /**
     * 
     * @type {boolean}
     * @memberof AddNewUserDTO
     */
    enabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof AddNewUserDTO
     */
    userLevel: AddNewUserDTOUserLevel;
    /**
     * 
     * @type {string}
     * @memberof AddNewUserDTO
     */
    password: string;
}

/**
    * @export
    * @enum {string}
    */
export enum AddNewUserDTOUserLevel {
    SuperUser = 'SuperUser',
    RegularUser = 'RegularUser',
    ViewOnlyUser = 'ViewOnlyUser'
}



