/* tslint:disable */
/* eslint-disable */
/**
 * Glista API
 * Glista ASP.NET Core Web API.
 *
 * The version of the OpenAPI document: v1
 * Contact: mitjajancic@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddNewScoringDTO
 */
export interface AddNewScoringDTO {
    /**
     * 
     * @type {string}
     * @memberof AddNewScoringDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AddNewScoringDTO
     */
    parameters: string;
    /**
     * 
     * @type {string}
     * @memberof AddNewScoringDTO
     */
    type: AddNewScoringDTOType;
    /**
     * 
     * @type {Array<string>}
     * @memberof AddNewScoringDTO
     */
    nationalities: Array<string>;
    /**
     * 
     * @type {Array<number>}
     * @memberof AddNewScoringDTO
     */
    points?: Array<number> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AddNewScoringDTO
     */
    tables: Array<AddNewScoringDTOTables>;
}

/**
    * @export
    * @enum {string}
    */
export enum AddNewScoringDTOType {
    Time = 'Time',
    Points = 'Points',
    Position = 'Position'
}
/**
    * @export
    * @enum {string}
    */
export enum AddNewScoringDTOTables {
    Overall = 'Overall',
    EnA = 'EnA',
    EnB = 'EnB',
    EnC = 'EnC',
    EnD = 'EnD',
    EnCcc = 'EnCCC',
    Female = 'Female',
    Team = 'Team'
}



