/* tslint:disable */
/* eslint-disable */
/**
 * Glista API
 * Glista ASP.NET Core Web API.
 *
 * The version of the OpenAPI document: v1
 * Contact: mitjajancic@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EditEventGroupDTO
 */
export interface EditEventGroupDTO {
    /**
     * 
     * @type {number}
     * @memberof EditEventGroupDTO
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof EditEventGroupDTO
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof EditEventGroupDTO
     */
    enabled: boolean;
}


