/* tslint:disable */
/* eslint-disable */
/**
 * Glista API
 * Glista ASP.NET Core Web API.
 *
 * The version of the OpenAPI document: v1
 * Contact: mitjajancic@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EditScoringDTO
 */
export interface EditScoringDTO {
    /**
     * 
     * @type {number}
     * @memberof EditScoringDTO
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof EditScoringDTO
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof EditScoringDTO
     */
    enabled: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditScoringDTO
     */
    nationalities: Array<string>;
    /**
     * 
     * @type {Array<number>}
     * @memberof EditScoringDTO
     */
    points?: Array<number> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditScoringDTO
     */
    tables: Array<EditScoringDTOTables>;
}

/**
    * @export
    * @enum {string}
    */
export enum EditScoringDTOTables {
    Overall = 'Overall',
    EnA = 'EnA',
    EnB = 'EnB',
    EnC = 'EnC',
    EnD = 'EnD',
    EnCcc = 'EnCCC',
    Female = 'Female',
    Team = 'Team'
}



