/* tslint:disable */
/* eslint-disable */
/**
 * Glista API
 * Glista ASP.NET Core Web API.
 *
 * The version of the OpenAPI document: v1
 * Contact: mitjajancic@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EditEventGroupPilotDTO
 */
export interface EditEventGroupPilotDTO {
    /**
     * 
     * @type {number}
     * @memberof EditEventGroupPilotDTO
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof EditEventGroupPilotDTO
     */
    teamId: number;
    /**
     * 
     * @type {number}
     * @memberof EditEventGroupPilotDTO
     */
    pilotId: number;
    /**
     * 
     * @type {number}
     * @memberof EditEventGroupPilotDTO
     */
    eventGroupId: number;
}


