/* tslint:disable */
/* eslint-disable */
/**
 * Glista API
 * Glista ASP.NET Core Web API.
 *
 * The version of the OpenAPI document: v1
 * Contact: mitjajancic@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BasicInfoDTO } from './basic-info-dto';

/**
 * 
 * @export
 * @interface EventDTO
 */
export interface EventDTO {
    /**
     * 
     * @type {number}
     * @memberof EventDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof EventDTO
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof EventDTO
     */
    utc?: number;
    /**
     * 
     * @type {string}
     * @memberof EventDTO
     */
    startDate?: string;
    /**
     * 
     * @type {string}
     * @memberof EventDTO
     */
    endDate?: string;
    /**
     * 
     * @type {string}
     * @memberof EventDTO
     */
    location?: string | null;
    /**
     * 
     * @type {BasicInfoDTO}
     * @memberof EventDTO
     */
    eventGroup?: BasicInfoDTO;
    /**
     * 
     * @type {string}
     * @memberof EventDTO
     */
    createdDate?: string;
    /**
     * 
     * @type {BasicInfoDTO}
     * @memberof EventDTO
     */
    file?: BasicInfoDTO;
}


