/* tslint:disable */
/* eslint-disable */
/**
 * Glista API
 * Glista ASP.NET Core Web API.
 *
 * The version of the OpenAPI document: v1
 * Contact: mitjajancic@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BasicInfoDTO } from './basic-info-dto';

/**
 * 
 * @export
 * @interface EventGroupPilotDTO
 */
export interface EventGroupPilotDTO {
    /**
     * 
     * @type {number}
     * @memberof EventGroupPilotDTO
     */
    id?: number;
    /**
     * 
     * @type {BasicInfoDTO}
     * @memberof EventGroupPilotDTO
     */
    team?: BasicInfoDTO;
    /**
     * 
     * @type {BasicInfoDTO}
     * @memberof EventGroupPilotDTO
     */
    pilot?: BasicInfoDTO;
    /**
     * 
     * @type {BasicInfoDTO}
     * @memberof EventGroupPilotDTO
     */
    eventGroup?: BasicInfoDTO;
}


