/* tslint:disable */
/* eslint-disable */
/**
 * Glista API
 * Glista ASP.NET Core Web API.
 *
 * The version of the OpenAPI document: v1
 * Contact: mitjajancic@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BasicInfoDTO } from './basic-info-dto';

/**
 * 
 * @export
 * @interface EventGroupDTO
 */
export interface EventGroupDTO {
    /**
     * 
     * @type {number}
     * @memberof EventGroupDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof EventGroupDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EventGroupDTO
     */
    createdDate?: string;
    /**
     * 
     * @type {string}
     * @memberof EventGroupDTO
     */
    updatedDate?: string;
    /**
     * 
     * @type {BasicInfoDTO}
     * @memberof EventGroupDTO
     */
    scoring?: BasicInfoDTO;
    /**
     * 
     * @type {boolean}
     * @memberof EventGroupDTO
     */
    enabled?: boolean;
}


