/* tslint:disable */
/* eslint-disable */
/**
 * Glista API
 * Glista ASP.NET Core Web API.
 *
 * The version of the OpenAPI document: v1
 * Contact: mitjajancic@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FileDTO
 */
export interface FileDTO {
    /**
     * 
     * @type {number}
     * @memberof FileDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FileDTO
     */
    path?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileDTO
     */
    uploadedDate?: string;
    /**
     * 
     * @type {number}
     * @memberof FileDTO
     */
    userId?: number;
}


