/* tslint:disable */
/* eslint-disable */
/**
 * Glista API
 * Glista ASP.NET Core Web API.
 *
 * The version of the OpenAPI document: v1
 * Contact: mitjajancic@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GliderDTO
 */
export interface GliderDTO {
    /**
     * 
     * @type {number}
     * @memberof GliderDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GliderDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GliderDTO
     */
    company?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GliderDTO
     */
    safetyClass?: GliderDTOSafetyClass;
    /**
     * 
     * @type {string}
     * @memberof GliderDTO
     */
    createdDate?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum GliderDTOSafetyClass {
    EnA = 'EnA',
    EnB = 'EnB',
    EnC = 'EnC',
    EnD = 'EnD',
    EnCcc = 'EnCCC',
    Other = 'Other'
}



