/* tslint:disable */
/* eslint-disable */
/**
 * Glista API
 * Glista ASP.NET Core Web API.
 *
 * The version of the OpenAPI document: v1
 * Contact: mitjajancic@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PilotDTO
 */
export interface PilotDTO {
    /**
     * 
     * @type {number}
     * @memberof PilotDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    nationalityCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    birthday?: string;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    createdDate?: string;
    /**
     * 
     * @type {string}
     * @memberof PilotDTO
     */
    updatedDate?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PilotDTO
     */
    civlId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PilotDTO
     */
    female?: boolean;
}


