/* tslint:disable */
/* eslint-disable */
/**
 * Glista API
 * Glista ASP.NET Core Web API.
 *
 * The version of the OpenAPI document: v1
 * Contact: mitjajancic@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ScoringDTO
 */
export interface ScoringDTO {
    /**
     * 
     * @type {number}
     * @memberof ScoringDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ScoringDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScoringDTO
     */
    parameters?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScoringDTO
     */
    type?: ScoringDTOType;
    /**
     * 
     * @type {boolean}
     * @memberof ScoringDTO
     */
    enabled?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ScoringDTO
     */
    nationalities?: Array<string> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof ScoringDTO
     */
    points?: Array<number> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ScoringDTO
     */
    tables?: Array<ScoringDTOTables>;
}

/**
    * @export
    * @enum {string}
    */
export enum ScoringDTOType {
    Time = 'Time',
    Points = 'Points',
    Position = 'Position'
}
/**
    * @export
    * @enum {string}
    */
export enum ScoringDTOTables {
    Overall = 'Overall',
    EnA = 'EnA',
    EnB = 'EnB',
    EnC = 'EnC',
    EnD = 'EnD',
    EnCcc = 'EnCCC',
    Female = 'Female',
    Team = 'Team'
}



