/* tslint:disable */
/* eslint-disable */
/**
 * Glista API
 * Glista ASP.NET Core Web API.
 *
 * The version of the OpenAPI document: v1
 * Contact: mitjajancic@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TaskPointDTO
 */
export interface TaskPointDTO {
    /**
     * 
     * @type {number}
     * @memberof TaskPointDTO
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskPointDTO
     */
    taskId?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskPointDTO
     */
    position?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TaskPointDTO
     */
    sss?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TaskPointDTO
     */
    ess?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TaskPointDTO
     */
    radius?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskPointDTO
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TaskPointDTO
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskPointDTO
     */
    longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskPointDTO
     */
    altitude?: number;
}


