/* tslint:disable */
/* eslint-disable */
/**
 * Glista API
 * Glista ASP.NET Core Web API.
 *
 * The version of the OpenAPI document: v1
 * Contact: mitjajancic@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { AddNewEventGroupDTO } from '../model';
// @ts-ignore
import { EditEventGroupDTO } from '../model';
// @ts-ignore
import { EventGroupDTO } from '../model';
/**
 * EventGroupApi - axios parameter creator
 * @export
 */
export const EventGroupApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {boolean} [enabled] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEventGroupGetEventGroupsGet: async (enabled?: boolean, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/EventGroup/GetEventGroups`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (enabled !== undefined) {
                localVarQueryParameter['enabled'] = enabled;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEventGroupIdDelete: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiEventGroupIdDelete', 'id', id)
            const localVarPath = `/api/EventGroup/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEventGroupIdGet: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiEventGroupIdGet', 'id', id)
            const localVarPath = `/api/EventGroup/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {EditEventGroupDTO} [editEventGroupDTO] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEventGroupIdPut: async (id: number, editEventGroupDTO?: EditEventGroupDTO, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiEventGroupIdPut', 'id', id)
            const localVarPath = `/api/EventGroup/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(editEventGroupDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {AddNewEventGroupDTO} [addNewEventGroupDTO] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEventGroupPost: async (addNewEventGroupDTO?: AddNewEventGroupDTO, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/EventGroup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addNewEventGroupDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EventGroupApi - functional programming interface
 * @export
 */
export const EventGroupApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EventGroupApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {boolean} [enabled] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEventGroupGetEventGroupsGet(enabled?: boolean, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<EventGroupDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiEventGroupGetEventGroupsGet(enabled, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEventGroupIdDelete(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiEventGroupIdDelete(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEventGroupIdGet(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EventGroupDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiEventGroupIdGet(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} id 
         * @param {EditEventGroupDTO} [editEventGroupDTO] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEventGroupIdPut(id: number, editEventGroupDTO?: EditEventGroupDTO, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiEventGroupIdPut(id, editEventGroupDTO, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {AddNewEventGroupDTO} [addNewEventGroupDTO] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEventGroupPost(addNewEventGroupDTO?: AddNewEventGroupDTO, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EventGroupDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiEventGroupPost(addNewEventGroupDTO, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * EventGroupApi - factory interface
 * @export
 */
export const EventGroupApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EventGroupApiFp(configuration)
    return {
        /**
         * 
         * @param {boolean} [enabled] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEventGroupGetEventGroupsGet(enabled?: boolean, options?: any): AxiosPromise<Array<EventGroupDTO>> {
            return localVarFp.apiEventGroupGetEventGroupsGet(enabled, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEventGroupIdDelete(id: number, options?: any): AxiosPromise<void> {
            return localVarFp.apiEventGroupIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEventGroupIdGet(id: number, options?: any): AxiosPromise<EventGroupDTO> {
            return localVarFp.apiEventGroupIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 
         * @param {EditEventGroupDTO} [editEventGroupDTO] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEventGroupIdPut(id: number, editEventGroupDTO?: EditEventGroupDTO, options?: any): AxiosPromise<void> {
            return localVarFp.apiEventGroupIdPut(id, editEventGroupDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AddNewEventGroupDTO} [addNewEventGroupDTO] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEventGroupPost(addNewEventGroupDTO?: AddNewEventGroupDTO, options?: any): AxiosPromise<EventGroupDTO> {
            return localVarFp.apiEventGroupPost(addNewEventGroupDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EventGroupApi - object-oriented interface
 * @export
 * @class EventGroupApi
 * @extends {BaseAPI}
 */
export class EventGroupApi extends BaseAPI {
    /**
     * 
     * @param {boolean} [enabled] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventGroupApi
     */
    public apiEventGroupGetEventGroupsGet(enabled?: boolean, options?: any) {
        return EventGroupApiFp(this.configuration).apiEventGroupGetEventGroupsGet(enabled, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventGroupApi
     */
    public apiEventGroupIdDelete(id: number, options?: any) {
        return EventGroupApiFp(this.configuration).apiEventGroupIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventGroupApi
     */
    public apiEventGroupIdGet(id: number, options?: any) {
        return EventGroupApiFp(this.configuration).apiEventGroupIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id 
     * @param {EditEventGroupDTO} [editEventGroupDTO] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventGroupApi
     */
    public apiEventGroupIdPut(id: number, editEventGroupDTO?: EditEventGroupDTO, options?: any) {
        return EventGroupApiFp(this.configuration).apiEventGroupIdPut(id, editEventGroupDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AddNewEventGroupDTO} [addNewEventGroupDTO] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventGroupApi
     */
    public apiEventGroupPost(addNewEventGroupDTO?: AddNewEventGroupDTO, options?: any) {
        return EventGroupApiFp(this.configuration).apiEventGroupPost(addNewEventGroupDTO, options).then((request) => request(this.axios, this.basePath));
    }
}
