/* tslint:disable */
/* eslint-disable */
/**
 * Glista API
 * Glista ASP.NET Core Web API.
 *
 * The version of the OpenAPI document: v1
 * Contact: mitjajancic@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { PilotDTO } from '../model';
/**
 * PilotApi - axios parameter creator
 * @export
 */
export const PilotApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} [civlId] 
         * @param {string} [nationalityCode] 
         * @param {string} [birthdayAfter] 
         * @param {string} [birthdayBefore] 
         * @param {boolean} [isFemale] 
         * @param {string} [firstName] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPilotGetPilotsGet: async (civlId?: number, nationalityCode?: string, birthdayAfter?: string, birthdayBefore?: string, isFemale?: boolean, firstName?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Pilot/GetPilots`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (civlId !== undefined) {
                localVarQueryParameter['civlId'] = civlId;
            }

            if (nationalityCode !== undefined) {
                localVarQueryParameter['nationalityCode'] = nationalityCode;
            }

            if (birthdayAfter !== undefined) {
                localVarQueryParameter['birthdayAfter'] = (birthdayAfter as any instanceof Date) ?
                    (birthdayAfter as any).toISOString() :
                    birthdayAfter;
            }

            if (birthdayBefore !== undefined) {
                localVarQueryParameter['birthdayBefore'] = (birthdayBefore as any instanceof Date) ?
                    (birthdayBefore as any).toISOString() :
                    birthdayBefore;
            }

            if (isFemale !== undefined) {
                localVarQueryParameter['isFemale'] = isFemale;
            }

            if (firstName !== undefined) {
                localVarQueryParameter['firstName'] = firstName;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPilotIdGet: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiPilotIdGet', 'id', id)
            const localVarPath = `/api/Pilot/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PilotApi - functional programming interface
 * @export
 */
export const PilotApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PilotApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} [civlId] 
         * @param {string} [nationalityCode] 
         * @param {string} [birthdayAfter] 
         * @param {string} [birthdayBefore] 
         * @param {boolean} [isFemale] 
         * @param {string} [firstName] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPilotGetPilotsGet(civlId?: number, nationalityCode?: string, birthdayAfter?: string, birthdayBefore?: string, isFemale?: boolean, firstName?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PilotDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiPilotGetPilotsGet(civlId, nationalityCode, birthdayAfter, birthdayBefore, isFemale, firstName, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPilotIdGet(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PilotDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiPilotIdGet(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * PilotApi - factory interface
 * @export
 */
export const PilotApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PilotApiFp(configuration)
    return {
        /**
         * 
         * @param {number} [civlId] 
         * @param {string} [nationalityCode] 
         * @param {string} [birthdayAfter] 
         * @param {string} [birthdayBefore] 
         * @param {boolean} [isFemale] 
         * @param {string} [firstName] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPilotGetPilotsGet(civlId?: number, nationalityCode?: string, birthdayAfter?: string, birthdayBefore?: string, isFemale?: boolean, firstName?: string, options?: any): AxiosPromise<Array<PilotDTO>> {
            return localVarFp.apiPilotGetPilotsGet(civlId, nationalityCode, birthdayAfter, birthdayBefore, isFemale, firstName, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPilotIdGet(id: number, options?: any): AxiosPromise<PilotDTO> {
            return localVarFp.apiPilotIdGet(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PilotApi - object-oriented interface
 * @export
 * @class PilotApi
 * @extends {BaseAPI}
 */
export class PilotApi extends BaseAPI {
    /**
     * 
     * @param {number} [civlId] 
     * @param {string} [nationalityCode] 
     * @param {string} [birthdayAfter] 
     * @param {string} [birthdayBefore] 
     * @param {boolean} [isFemale] 
     * @param {string} [firstName] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PilotApi
     */
    public apiPilotGetPilotsGet(civlId?: number, nationalityCode?: string, birthdayAfter?: string, birthdayBefore?: string, isFemale?: boolean, firstName?: string, options?: any) {
        return PilotApiFp(this.configuration).apiPilotGetPilotsGet(civlId, nationalityCode, birthdayAfter, birthdayBefore, isFemale, firstName, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PilotApi
     */
    public apiPilotIdGet(id: number, options?: any) {
        return PilotApiFp(this.configuration).apiPilotIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }
}
