/* tslint:disable */
/* eslint-disable */
/**
 * Glista API
 * Glista ASP.NET Core Web API.
 *
 * The version of the OpenAPI document: v1
 * Contact: mitjajancic@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { TaskPointDTO } from '../model';
/**
 * TaskPointApi - axios parameter creator
 * @export
 */
export const TaskPointApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} [taskId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTaskPointGetTaskPointsGet: async (taskId?: number, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/TaskPoint/GetTaskPoints`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (taskId !== undefined) {
                localVarQueryParameter['taskId'] = taskId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTaskPointIdGet: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiTaskPointIdGet', 'id', id)
            const localVarPath = `/api/TaskPoint/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TaskPointApi - functional programming interface
 * @export
 */
export const TaskPointApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TaskPointApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} [taskId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTaskPointGetTaskPointsGet(taskId?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TaskPointDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiTaskPointGetTaskPointsGet(taskId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTaskPointIdGet(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskPointDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiTaskPointIdGet(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TaskPointApi - factory interface
 * @export
 */
export const TaskPointApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TaskPointApiFp(configuration)
    return {
        /**
         * 
         * @param {number} [taskId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTaskPointGetTaskPointsGet(taskId?: number, options?: any): AxiosPromise<Array<TaskPointDTO>> {
            return localVarFp.apiTaskPointGetTaskPointsGet(taskId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTaskPointIdGet(id: number, options?: any): AxiosPromise<TaskPointDTO> {
            return localVarFp.apiTaskPointIdGet(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TaskPointApi - object-oriented interface
 * @export
 * @class TaskPointApi
 * @extends {BaseAPI}
 */
export class TaskPointApi extends BaseAPI {
    /**
     * 
     * @param {number} [taskId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskPointApi
     */
    public apiTaskPointGetTaskPointsGet(taskId?: number, options?: any) {
        return TaskPointApiFp(this.configuration).apiTaskPointGetTaskPointsGet(taskId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskPointApi
     */
    public apiTaskPointIdGet(id: number, options?: any) {
        return TaskPointApiFp(this.configuration).apiTaskPointIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }
}
